
<style>.breadcrumbs{display: none;}</style>
<?php 
$_helper = $this->helper('catalog/output'); 
$_product = $this->getProduct(); 
$category=$_product->getCategoryIds();
$web=mage::getSingleton('web/web');
$web->connectMemcache();
$supplierhelper= Mage::helper('web');
$suppliercode = "spotcity_supplier";


$supplierlabel=$web->getMemcache('spotcitysupplier-'.$_product->getSpotcitySupplier().'-'.$suppliercode);
if($supplierlabel=="" || $supplierlabel==false || $supplierlabel==-1){
	$supplierlabel=$_product->getAttributeText($suppliercode);
	$web->setMemcache('spotcitysupplier-'.$_product->getSpotcitySupplier().'-'.$suppliercode,$supplierlabel,'86400');
}
//$supplierid= $supplierhelper->attributeValueExistsId($suppliercode,$supplierlabel);
//$companyarr= $supplierhelper->getidcompany($_product->getAttributeText($suppliercode));
//$supplierinformation = $supplierhelper->supplierinfomations($companyarr[$_product->getAttributeText($suppliercode)]);

$supplierinformation=$web->getMemcache('spotcitysupplier-'.$_product->getSpotcitySupplier());
if($supplierinformation=="" || $supplierinformation==false || $supplierinformation==-1){
	$supplierinformation= $supplierhelper->supplierinfomations($_product->getSpotcitySupplier());
	$web->setMemcache('spotcitysupplier-'.$_product->getSpotcitySupplier(),$supplierinformation,'86400');
}

#lay latlong
	function get_lat_long($address=''){
		$address = str_replace(" ", "+", $address);
	
		$json = file_get_contents("http://maps.google.com/maps/api/geocode/json?address=$address&sensor=false");
		$json = json_decode($json);
	
		$lat = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lat'};
		$long = $json->{'results'}[0]->{'geometry'}->{'location'}->{'lng'};
		if($lat != '' && $long != ''){
			return $lat.','.$long;
		}else{
			return '';
		}
	}
	if($supplierinformation['lat'] == '' || $supplierinformation['long'] == ''){
		if($supplierinformation['address'] != ''){
			$addressArr = explode('-',$supplierinformation['address']);
			$address = $addressArr[0];
			foreach($addressArr as $addresss){
				if(strlen($address) < strlen($addresss)){
					$address = $addresss;
				}
			}
		}
		$google_location = $address.' '.$supplierinformation['plz'].' '.$supplierinformation['city'];
		$google_location = str_replace("  ", " ", $google_location);
		$latlong = get_lat_long(utf8_encode($supplierinformation['google_location']));
		if($latlong != ''){
			$supplierhelper -> updatelatlong($supplierinformation['typo3_id'],$latlong);
			$google_location = $supplierinformation['google_location'];
		}else{
			$latlong = get_lat_long($google_location);
			if($latlong != ''){
				$supplierhelper -> updatelatlong($supplierinformation['typo3_id'],$latlong);
			}			
		}
	}
	$latlong=$supplierinformation['lat'].','.$supplierinformation['long'];
	$google_location = $supplierinformation['google_location'];
#END lay latlong
$checkdomains = Mage::getModel('ads/fedomain')->getCollection()
->addFieldToFilter('domainName', array('like'=>$supplierinformation['city'].'.%'))->getdata();

$friendlyurl = str_replace ( " ", "-", strtolower ( $supplierinformation ["option_value"] ) );
$friendlyurl = str_replace ( ".", "-", $friendlyurl );
$friendlyurl = str_replace ( "ü", "ue", $friendlyurl );
$friendlyurl = str_replace ( "ä", "ae", $friendlyurl );
$friendlyurl = str_replace ( "ö", "oe", $friendlyurl );
$friendlyurl = str_replace ( "ß", "ss", $friendlyurl );
$friendlyurl = str_replace ( "Ü", "ue", $friendlyurl );
$friendlyurl = str_replace ( "Ä", "ae", $friendlyurl );
$friendlyurl = str_replace ( "Ö", "oe", $friendlyurl );

$target_spotsite = "http://".$checkdomains[0]['domainName'] . "/company-detail/type/cdetail/" . $supplierinformation ["typo3_id"] . "/".$friendlyurl;
$arrangecates=array();
$tempcategory=array();
$cateandsubcat=array();
foreach($category as $data)
{   
	$cateinfo=Mage::getModel('catalog/category')->load($data)	;
    if($data != 3 && $data != 245)
        $cateandsubcat[] = $cateinfo["name"];
	$arrangecate["id"]=$cateinfo["entity_id"];
	$arrangecate["level"]=$cateinfo["level"];
	array_push($arrangecates,$arrangecate);
}
      
$countcategory=count($arrangecates);
for($i=1;$i<=$countcategory;$i++)
{
		foreach($arrangecates As $key=>$check)
		{
			if($check["level"]==$i)
				break;
		}	
		$categorystore[]=$arrangecates[$key]["id"];
}
$lastcategory=end($categorystore);
?>
<?php $catearr =  explode(" ", $cateandsubcat[0]); ?>
<script>
 Event.observe(window, 'load', function() {

	 <?php foreach($categorystore as $cateopen):?>

				if($('cate_<?php echo $cateopen;?>')!==null)
				{
                    $('cate_<?php echo $cateopen;?>').toggleClassName('grower CLOSE');
                    $('cate_<?php echo $cateopen;?>').addClassName('grower selected OPEN');
                    $('hidecate_<?php echo $cateopen;?>').show();
				}
				if($('csscate_<?php echo $cateopen;?>')!==null)
				{
                    $('csscate_<?php echo $lastcategory;?>').style.color="blue";
				}
        
            <?php endforeach;?>
        
    });
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    function redirect_to_spotsite(){
        
    	window.location = "<?php echo $target_spotsite ?>";
    }
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
 <h2>IHRE AUSWAHL : <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
<div class="product-page">
 <div class="row">
   <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>             
			<div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
			<div class="col-md-6 col-sm-6">
                  <div class="product-main-image">
                    <img src="<?php echo $this->getSkinUrl('images/products/model7.jpg');?>" alt="Cool green dress with red bell" class="img-responsive" data-BigImgsrc="<?php echo $this->getSkinUrl('images/products/model7.jpg');?>">
                  </div>
                  <div class="product-other-images margin-top-10">
                    <a href="<?php echo $this->getSkinUrl('images/products/model3.jpg');?>" class="fancybox-button" rel="photos-lib"><img alt="Berry Lace Dress" src="<?php echo $this->getSkinUrl('images/products/model3.jpg');?>"></a>
                    <a href="<?php echo $this->getSkinUrl('images/products/model4.jpg');?>" class="fancybox-button" rel="photos-lib"><img alt="Berry Lace Dress" src="<?php echo $this->getSkinUrl('images/products/model4.jpg');?>"></a>
                    <a href="<?php echo $this->getSkinUrl('images/products/model5.jpg');?>" class="fancybox-button" rel="photos-lib"><img alt="Berry Lace Dress" src="<?php echo $this->getSkinUrl('images/products/model5.jpg');?>"></a>
                  </div>
           </div>
                <div class="col-md-6 col-sm-6">
                  <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                  <div class="info-product-detail">
                  		<div class="product-section1">
                  			<p class="pull-left">Verkauf durch: </p>
                  		 	<div class="clearfix"></div>
                  			<ul class="">
                              	<li><a href="#">styled</a></li>
                              	<li><a href="#"><?php echo $cateandsubcat[1] ?>'s <?php echo $catearr[1]; ?></a></li>
                              	<li><a href="#"><?php echo ucfirst($supplierinformation['city']); ?></a></li>
                              	<li></li>
                              	<li class="print"><input type="button" name="Submit" onclick="redirect_to_spotsite()" value="Zur Spotsite" class="exclusive exclusive-new btn btn-default" role="button"/></li>
                         	</ul>
                  		</div>
                  		<div class="product-section2">
                  				<p style="clear: both;" id="product_reference">
                            			<label for="product_reference">Artikel-Nr: </label>
                            			<span class="editable"><?php echo $_product->getSku()?></span>
                            		</p>                                    
                                    <!-- short_description -->
                                    <div class="short_description_block">
                        				<div class="description">
                        					<p class="bodytext"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
                        			   </div>
                    			     </div>                                    
    								 <?php if ($_product->isSaleable() && $this->hasOptions()):?>                    
                                                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                                    <?php endif;?>
                  		</div>
                  			
                  </div>
                  <div class="clearfix"></div>
                  <div class="price-availability-block clearfix">
                    <?php echo $this->getChildHtml('product_type_data');?>
                    <!-- can thay doi code producy_type_data sang cau truc nhu the nay
                    <div class="price">
                      <strong><span>$</span>47.00</strong>
                      <em>$<span>62.00</span></em>
                    </div>
                    <div class="availability">
                      Availability: <strong>In Stock</strong>
                    </div>
                     -->
                  </div>
                 
                  <div class="product-page-options">
                    <div class="pull-left">
                      <label class="control-label">Size:</label>
                      <select class="form-control input-sm">
                        <option>L</option>
                        <option>M</option>
                        <option>XL</option>
                      </select>
                    </div>
                    <div class="pull-left">
                      <label class="control-label">Color:</label>
                      <select class="form-control input-sm">
                        <option>Red</option>
                        <option>Blue</option>
                        <option>Black</option>
                      </select>
                    </div>
                  </div>
                  <div class="product-page-cart">
                    <div class="product-quantity">
                        <input id="product-quantity" type="text" value="1" readonly class="form-control input-sm">
                    </div>
                    <button class="btn btn-primary" type="submit">Add to cart</button>
                  </div>
                  <div class="review">
                    <input type="range" value="4" step="0.25" id="backing4">
                    <div class="rateit" data-rateit-backingfld="#backing4" data-rateit-resetable="false"  data-rateit-ispreset="true" data-rateit-min="0" data-rateit-max="5">
                    </div>
                    <a href="javascript:;">7 reviews</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="javascript:;">Write a review</a>
                  </div>
                  <ul class="social-icons">
                    <li><a class="facebook" data-original-title="facebook" href="javascript:;"></a></li>
                    <li><a class="twitter" data-original-title="twitter" href="javascript:;"></a></li>
                    <li><a class="googleplus" data-original-title="googleplus" href="javascript:;"></a></li>
                    <li><a class="evernote" data-original-title="evernote" href="javascript:;"></a></li>
                    <li><a class="tumblr" data-original-title="tumblr" href="javascript:;"></a></li>
                  </ul>
                </div>
</form>
                <div class="product-page-content">
                  <ul id="myTab" class="nav nav-tabs">
                    <li><a href="#Description" data-toggle="tab">Description</a></li>
                    <li><a href="#Information" data-toggle="tab">Information</a></li>
                    <li class="active"><a href="#Reviews" data-toggle="tab">Reviews (2)</a></li>
                  </ul>
                  <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade" id="Description">
                      <p>Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed sit nonumy nibh sed euismod laoreet dolore magna aliquarm erat sit volutpat Nostrud duis molestie at dolore. </p>
                    </div>
                    <div class="tab-pane fade" id="Information">
                      <table class="datasheet">
                        <tr>
                          <th colspan="2">Additional features</th>
                        </tr>
                        <tr>
                          <td class="datasheet-features-type">Value 1</td>
                          <td>21 cm</td>
                        </tr>
                        <tr>
                          <td class="datasheet-features-type">Value 2</td>
                          <td>700 gr.</td>
                        </tr>
                        <tr>
                          <td class="datasheet-features-type">Value 3</td>
                          <td>10 person</td>
                        </tr>
                        <tr>
                          <td class="datasheet-features-type">Value 4</td>
                          <td>14 cm</td>
                        </tr>
                        <tr>
                          <td class="datasheet-features-type">Value 5</td>
                          <td>plastic</td>
                        </tr>
                      </table>
                    </div>
                    <div class="tab-pane fade in active" id="Reviews">
                      <!--<p>There are no reviews for this product.</p>-->
                      <div class="review-item clearfix">
                        <div class="review-item-submitted">
                          <strong>Bob</strong>
                          <em>30/12/2013 - 07:37</em>
                          <div class="rateit" data-rateit-value="5" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                        </div>                                              
                        <div class="review-item-content">
                            <p>Sed velit quam, auctor id semper a, hendrerit eget justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel arcu pulvinar dolor tempus feugiat id in orci. Phasellus sed erat leo. Donec luctus, justo eget ultricies tristique, enim mauris bibendum orci, a sodales lectus purus ut lorem.</p>
                        </div>
                      </div>
                      <div class="review-item clearfix">
                        <div class="review-item-submitted">
                          <strong>Mary</strong>
                          <em>13/12/2013 - 17:49</em>
                          <div class="rateit" data-rateit-value="2.5" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                        </div>                                              
                        <div class="review-item-content">
                            <p>Sed velit quam, auctor id semper a, hendrerit eget justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel arcu pulvinar dolor tempus feugiat id in orci. Phasellus sed erat leo. Donec luctus, justo eget ultricies tristique, enim mauris bibendum orci, a sodales lectus purus ut lorem.</p>
                        </div>
                      </div>

                      <!-- BEGIN FORM-->
                      <form action="#" class="reviews-form" role="form">
                        <h2>Write a review</h2>
                        <div class="form-group">
                          <label for="name">Name <span class="require">*</span></label>
                          <input type="text" class="form-control" id="name">
                        </div>
                        <div class="form-group">
                          <label for="email">Email</label>
                          <input type="text" class="form-control" id="email">
                        </div>
                        <div class="form-group">
                          <label for="review">Review <span class="require">*</span></label>
                          <textarea class="form-control" rows="8" id="review"></textarea>
                        </div>
                        <div class="form-group">
                          <label for="email">Rating</label>
                          <input type="range" value="4" step="0.25" id="backing5">
                          <div class="rateit" data-rateit-backingfld="#backing5" data-rateit-resetable="false"  data-rateit-ispreset="true" data-rateit-min="0" data-rateit-max="5">
                          </div>
                        </div>
                        <div class="padding-top-20">                  
                          <button type="submit" class="btn btn-primary">Send</button>
                        </div>
                      </form>
                      <!-- END FORM--> 
                    </div>
                  </div>
                </div>

               
                </div>
                </div>